version: "3.9"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      USER_NAME: admin
      USER_PWD: password
      DB_URL: host.docker.internal
    depends_on:
      - db
  # api-tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - .:/usr/src/app
  #   depends_on:
  #     - db
volumes:
  mongo-data:
